## StudyData.gd
## Autoload singleton (Project Settings -> Autoload -> add this as "StudyData").
##
## Holds question banks for the school/study scene. Each question is a
## Dictionary: {"question": String, "options": Array[String], "correct": int}
## where "correct" is the index into "options".
extends Node

var _banks: Dictionary = {
	"english": [
		{"question": "What literary technique gives human qualities to non-human things?",
			"options": ["Personification", "Alliteration", "Onomatopoeia", "Hyperbole"], "correct": 0},
		{"question": "Which text type presents one side of an argument persuasively?",
			"options": ["Narrative", "Expository", "Persuasive", "Descriptive"], "correct": 2},
		{"question": "What is a \"motif\" in a novel?",
			"options": ["A recurring element with symbolic significance", "The main character's name",
				"The setting of the story", "A twist ending"], "correct": 0},
		{"question": "In an analytical essay, what should a topic sentence do?",
			"options": ["Summarise the whole essay", "Introduce the main idea of the paragraph",
				"Provide a quote", "Conclude the essay"], "correct": 1},
		{"question": "Which word best describes a tone that is bitterly mocking?",
			"options": ["Sardonic", "Jubilant", "Melancholic", "Nostalgic"], "correct": 0},
		{"question": "What is dramatic irony?",
			"options": ["When the audience knows something the characters don't",
				"When two characters argue", "When the plot twists unexpectedly",
				"When a character speaks directly to the audience"], "correct": 0},
		{"question": "Which of these is an example of a simile?",
			"options": ["Her smile was a ray of sunshine", "Life is a highway",
				"Busy as a bee", "Time flies"], "correct": 2},
		{"question": "What does \"juxtaposition\" mean?",
			"options": ["Placing two contrasting things close together for effect",
				"Repeating a sound at the start of words", "A short poem about nature",
				"The climax of a story"], "correct": 0},
		{"question": "What is the term for a story told using \"I\" from a character's own perspective?",
			"options": ["First-person narrative", "Third-person omniscient",
				"Second-person narrative", "Stream of consciousness"], "correct": 0},
		{"question": "Which best defines \"connotation\"?",
			"options": ["The implied or associated meaning of a word", "The literal dictionary meaning",
				"A rhyme scheme", "A type of stanza"], "correct": 0},
		{"question": "What is an \"unreliable narrator\"?",
			"options": ["A narrator whose credibility is compromised", "A narrator who speaks in verse",
				"A narrator who is also the author", "A narrator who never speaks"], "correct": 0},
		{"question": "In poetry, what is enjambment?",
			"options": ["A sentence that runs onto the next line without a pause",
				"A rhyme at the end of two lines", "A pattern of stressed and unstressed syllables",
				"A repeated word at the start of lines"], "correct": 0},
		{"question": "What does \"in medias res\" mean?",
			"options": ["Starting a story in the middle of the action", "Ending on a cliffhanger",
				"Telling a story out of order", "Using multiple narrators"], "correct": 0},
		{"question": "Which device repeats consonant sounds at the start of nearby words?",
			"options": ["Alliteration", "Assonance", "Consonance", "Sibilance"], "correct": 0},
		{"question": "What is a soliloquy?",
			"options": ["A speech a character gives alone, revealing inner thoughts",
				"A conversation between two characters", "A song within a play",
				"The play's final scene"], "correct": 0},
		{"question": "Which technique hints at events to come through ominous imagery or dialogue?",
			"options": ["Foreshadowing", "Flashback", "Symbolism", "Allegory"], "correct": 0},
		{"question": "What's the purpose of a rhetorical question in a persuasive speech?",
			"options": ["To make the audience think without expecting an answer",
				"To ask for information", "To confuse the reader", "To end the speech"], "correct": 0},
		{"question": "What is the climax of a story?",
			"options": ["The turning point of highest tension", "The opening scene",
				"The introduction of characters", "The resolution"], "correct": 0},
		{"question": "Which term describes writing that criticises society using humour or exaggeration?",
			"options": ["Satire", "Elegy", "Ode", "Sonnet"], "correct": 0},
		{"question": "What is an antagonist?",
			"options": ["The character who opposes the protagonist", "The narrator of the story",
				"The setting of the story", "A minor background character"], "correct": 0},
		{"question": "What does \"pathos\" appeal to in an argument?",
			"options": ["The audience's emotions", "Logic and reason",
				"The speaker's credibility", "Statistics"], "correct": 0},
		{"question": "Which best describes \"ethos\" in rhetoric?",
			"options": ["An appeal based on the credibility of the speaker", "An appeal to emotion",
				"An appeal to logic", "A metaphor"], "correct": 0},
		{"question": "What is a \"sonnet\"?",
			"options": ["A 14-line poem with a specific rhyme scheme", "A four-line stanza",
				"A poem with no rhyme", "A speech given by one character"], "correct": 0},
		{"question": "What does \"verisimilitude\" refer to in fiction?",
			"options": ["The appearance of being true or real", "A plot twist",
				"A character flaw", "The setting of a story"], "correct": 0},
		{"question": "Which of these is an example of assonance?",
			"options": ["The rain in Spain falls mainly on the plain", "Peter Piper picked a peck",
				"The wind whispered softly", "Busy as a bee"], "correct": 0},
		{"question": "What effect do short, fragmented sentences have in a tense scene?",
			"options": ["They build urgency and pace", "They slow the pace and calm the reader",
				"They confuse the timeline", "They add humour"], "correct": 0},
		{"question": "What is a bildungsroman?",
			"options": ["A novel about a character's moral and psychological growth",
				"A poem about nature", "A play with no dialogue", "A story with multiple endings"],
			"correct": 0},
		{"question": "In an essay, what does a \"counter-argument\" do?",
			"options": ["Acknowledges an opposing view before responding to it", "Repeats the thesis",
				"Introduces a new topic", "Concludes the essay"], "correct": 0},
		{"question": "What is the term for the attitude an author takes towards their subject?",
			"options": ["Tone", "Mood", "Diction", "Syntax"], "correct": 0},
		{"question": "What is \"mood\" in a text?",
			"options": ["The atmosphere or feeling created for the reader", "The author's opinion",
				"The main character's personality", "The historical setting"], "correct": 0},
		{"question": "What is a \"flashback\" in narrative structure?",
			"options": ["A scene that interrupts the present to show an earlier event",
				"A scene set in the future", "A dream sequence only", "The story's final scene"],
			"correct": 0},
		{"question": "What does \"diction\" refer to in a text?",
			"options": ["The writer's choice of words", "The rhythm of a poem",
				"The structure of a paragraph", "The setting of a story"], "correct": 0},
		{"question": "What is a metaphor?",
			"options": ["A direct comparison between two unlike things, without \"like\" or \"as\"",
				"A comparison using \"like\" or \"as\"", "A word that imitates a sound",
				"An exaggeration for effect"], "correct": 0},
		{"question": "What is the purpose of an epilogue?",
			"options": ["To provide closure or a glimpse of the future after the story ends",
				"To introduce the setting", "To list the characters", "To summarise chapter one"],
			"correct": 0},
		{"question": "Which term describes a narrator who can access every character's thoughts?",
			"options": ["Third-person omniscient", "First-person limited", "Second-person",
				"Unreliable narrator"], "correct": 0},
		{"question": "What is \"syntax\" in writing?",
			"options": ["The arrangement of words and phrases to create sentences",
				"The meaning of a word", "The sound of a word", "The tone of a piece"], "correct": 0},
		{"question": "What does \"allegory\" mean?",
			"options": ["A story with a hidden moral or political meaning",
				"A story about animals only", "A type of rhyme scheme", "A humorous exaggeration"],
			"correct": 0},
		{"question": "In a persuasive text, what is a \"call to action\"?",
			"options": ["A statement urging the audience to do something", "A rhetorical question",
				"A statistic", "A personal anecdote"], "correct": 0},
		{"question": "What is the effect of using second-person narration (\"you\")?",
			"options": ["It draws the reader directly into the story as a participant",
				"It distances the reader from events", "It only works in poetry",
				"It removes all emotion"], "correct": 0},
		{"question": "What does \"hyperbole\" mean?",
			"options": ["Deliberate exaggeration for effect", "Understatement for effect",
				"A direct comparison", "Repetition of consonant sounds"], "correct": 0},
		{"question": "What is \"understatement\" used for?",
			"options": ["To downplay something for ironic or humorous effect",
				"To exaggerate something", "To describe a setting", "To summarise an argument"],
			"correct": 0},
		{"question": "What does a \"thesis statement\" do in an essay?",
			"options": ["States the essay's main argument or position", "Lists sources",
				"Describes the writer's biography", "Concludes the essay"], "correct": 0},
	],
	"maths": [
		{"question": "What is the derivative of x³?",
			"options": ["3x²", "x²", "3x", "x³ / 3"], "correct": 0},
		{"question": "Solve for x: 2x + 5 = 17",
			"options": ["x = 6", "x = 5", "x = 11", "x = 8"], "correct": 0},
		{"question": "What is the integral of 2x dx?",
			"options": ["x² + C", "2x² + C", "x + C", "2 + C"], "correct": 0},
		{"question": "What is log₂(8)?",
			"options": ["3", "2", "4", "8"], "correct": 0},
		{"question": "What is the derivative of sin(x)?",
			"options": ["cos(x)", "-cos(x)", "-sin(x)", "tan(x)"], "correct": 0},
		{"question": "What does the discriminant b² - 4ac tell you?",
			"options": ["The number of real roots", "The vertex of the parabola",
				"The y-intercept", "The axis of symmetry"], "correct": 0},
		{"question": "What is the gradient of the line y = 3x - 4?",
			"options": ["3", "-4", "4", "-3"], "correct": 0},
		{"question": "Simplify: (x² - 9) / (x - 3)",
			"options": ["x + 3", "x - 3", "x + 9", "x² - 3"], "correct": 0},
		{"question": "What is the derivative of cos(x)?",
			"options": ["-sin(x)", "sin(x)", "-cos(x)", "tan(x)"], "correct": 0},
		{"question": "What is d/dx of eˣ?",
			"options": ["eˣ", "x e^(x-1)", "e^(x-1)", "ln(x)"], "correct": 0},
		{"question": "What is the integral of 1/x dx?",
			"options": ["ln|x| + C", "1/x² + C", "x ln(x) + C", "-1/x² + C"], "correct": 0},
		{"question": "Factorise: x² - 5x + 6",
			"options": ["(x-2)(x-3)", "(x+2)(x+3)", "(x-1)(x-6)", "(x-2)(x+3)"], "correct": 0},
		{"question": "What is the value of sin(90°)?",
			"options": ["1", "0", "-1", "0.5"], "correct": 0},
		{"question": "What is the value of cos(0°)?",
			"options": ["1", "0", "-1", "0.5"], "correct": 0},
		{"question": "Solve: x² - 9 = 0",
			"options": ["x = ±3", "x = 3", "x = -3", "x = 9"], "correct": 0},
		{"question": "What is the quadratic formula for ax² + bx + c = 0?",
			"options": ["x = (-b ± sqrt(b²-4ac)) / 2a", "x = -b/2a", "x = b² - 4ac",
				"x = (b ± sqrt(a²-4bc))/2c"], "correct": 0},
		{"question": "What does \"differentiation\" measure?",
			"options": ["The rate of change of a function", "The area under a curve",
				"The sum of a series", "The average of a data set"], "correct": 0},
		{"question": "What is the definite integral used to calculate?",
			"options": ["The area under a curve", "The rate of change",
				"The slope of a tangent", "The derivative"], "correct": 0},
		{"question": "What is the mean of the data set: 2, 4, 6, 8, 10?",
			"options": ["6", "5", "8", "4"], "correct": 0},
		{"question": "What does standard deviation measure?",
			"options": ["The spread/variability of a data set", "The average value",
				"The total sum", "The mode"], "correct": 0},
		{"question": "What is 3! (3 factorial)?",
			"options": ["6", "3", "9", "1"], "correct": 0},
		{"question": "In a right triangle, which trig ratio equals opposite/hypotenuse?",
			"options": ["Sine", "Cosine", "Tangent", "Secant"], "correct": 0},
		{"question": "What is the sum of interior angles of a triangle?",
			"options": ["180°", "360°", "90°", "270°"], "correct": 0},
		{"question": "What is the value of pi to 2 decimal places?",
			"options": ["3.14", "3.41", "3.12", "3.16"], "correct": 0},
		{"question": "Solve for x: 3ˣ = 81",
			"options": ["x = 4", "x = 3", "x = 27", "x = 9"], "correct": 0},
		{"question": "What is the derivative of a constant?",
			"options": ["0", "1", "The constant itself", "Undefined"], "correct": 0},
		{"question": "Expand: (x + 2)²",
			"options": ["x² + 4x + 4", "x² + 2x + 4", "x² + 4x + 2", "x² + 4"], "correct": 0},
		{"question": "In y = mx + c, what does c represent?",
			"options": ["The y-intercept", "The gradient", "The x-intercept", "The turning point"],
			"correct": 0},
		{"question": "What is the probability of rolling a 6 on a fair six-sided die?",
			"options": ["1/6", "1/3", "1/2", "1/12"], "correct": 0},
		{"question": "What does it mean if two events are \"mutually exclusive\"?",
			"options": ["They cannot both happen at the same time", "They always happen together",
				"They are independent", "They have equal probability"], "correct": 0},
		{"question": "What is the derivative of tan(x)?",
			"options": ["sec²(x)", "sec(x)", "-sec²(x)", "csc(x)"], "correct": 0},
		{"question": "What is the value of cos(90°)?",
			"options": ["0", "1", "-1", "0.5"], "correct": 0},
		{"question": "Simplify: 2³ x 2⁴",
			"options": ["2⁷", "2¹²", "4⁷", "2¹"], "correct": 0},
		{"question": "What is the formula for the area of a circle?",
			"options": ["πr²", "2πr", "πd", "r²"], "correct": 0},
		{"question": "What is the formula for the circumference of a circle?",
			"options": ["2πr", "πr²", "πd/2", "r²"], "correct": 0},
		{"question": "Solve: |x - 4| = 6",
			"options": ["x = 10 or x = -2", "x = 10 only", "x = -2 only", "x = 6"], "correct": 0},
		{"question": "What is the sum of 2, 4, 6, 8, 10?",
			"options": ["30", "20", "25", "35"], "correct": 0},
		{"question": "What does \"asymptote\" mean on a graph?",
			"options": ["A line a curve approaches but never touches",
				"A point where the curve crosses the x-axis", "The maximum value of a function",
				"The midpoint of a curve"], "correct": 0},
		{"question": "What is the derivative of ln(x)?",
			"options": ["1/x", "x", "ln(x)", "1/x²"], "correct": 0},
		{"question": "What is the value of 10⁰?",
			"options": ["1", "0", "10", "Undefined"], "correct": 0},
		{"question": "Which of these is a Pythagorean triple?",
			"options": ["3, 4, 5", "2, 3, 4", "5, 6, 7", "1, 2, 3"], "correct": 0},
		{"question": "What is the median of: 3, 7, 9, 15, 20?",
			"options": ["9", "7", "15", "11"], "correct": 0},
	],
	"physics": [
		{"question": "What is Newton's Second Law expressed as?",
			"options": ["F = ma", "F = mv", "E = mc²", "p = mv"], "correct": 0},
		{"question": "What is the SI unit of force?",
			"options": ["Newton", "Joule", "Watt", "Pascal"], "correct": 0},
		{"question": "An object in free fall on Earth accelerates at approximately what rate?",
			"options": ["9.8 m/s²", "10 m/s", "8.9 m/s²", "9.8 km/s²"], "correct": 0},
		{"question": "What does the area under a velocity-time graph represent?",
			"options": ["Displacement", "Acceleration", "Force", "Speed"], "correct": 0},
		{"question": "Which of these quantities is a vector?",
			"options": ["Velocity", "Speed", "Distance", "Energy"], "correct": 0},
		{"question": "What is the formula for kinetic energy?",
			"options": ["1/2 m v²", "m v²", "m g h", "1/2 m v"], "correct": 0},
		{"question": "What happens to total momentum in a closed system during a collision?",
			"options": ["It is conserved", "It doubles", "It disappears", "It converts to heat only"],
			"correct": 0},
		{"question": "What is the SI unit of electrical resistance?",
			"options": ["Ohm", "Volt", "Amp", "Watt"], "correct": 0},
		{"question": "What is the formula for gravitational potential energy?",
			"options": ["m g h", "1/2 m v²", "F d", "m c²"], "correct": 0},
		{"question": "What is Ohm's Law?",
			"options": ["V = IR", "P = IV", "F = ma", "E = mc²"], "correct": 0},
		{"question": "What is the formula for power in an electrical circuit?",
			"options": ["P = IV", "P = IR", "P = V/I", "P = I/V"], "correct": 0},
		{"question": "What does \"wavelength\" measure?",
			"options": ["The distance between two successive wave crests", "The speed of a wave",
				"The height of a wave", "The frequency of a wave"], "correct": 0},
		{"question": "What is the relationship between frequency (f) and period (T)?",
			"options": ["T = 1/f", "T = f", "T = 2f", "T = f²"], "correct": 0},
		{"question": "What is Newton's Third Law?",
			"options": ["For every action there is an equal and opposite reaction",
				"Objects in motion stay in motion", "Force equals mass times acceleration",
				"Energy cannot be created or destroyed"], "correct": 0},
		{"question": "What is the law of conservation of energy?",
			"options": ["Energy cannot be created or destroyed, only transformed",
				"Energy always increases over time", "Energy is only kinetic",
				"Energy is measured in Newtons"], "correct": 0},
		{"question": "What is the SI unit of electrical charge?",
			"options": ["Coulomb", "Ampere", "Volt", "Ohm"], "correct": 0},
		{"question": "What is the approximate speed of light in a vacuum?",
			"options": ["3 x 10⁸ m/s", "3 x 10⁶ m/s", "3 x 10⁵ m/s", "3 x 10¹⁰ m/s"], "correct": 0},
		{"question": "What type of wave is sound?",
			"options": ["Longitudinal", "Transverse", "Electromagnetic", "Standing"], "correct": 0},
		{"question": "What causes an object to undergo projectile motion?",
			"options": ["Gravity acting on a horizontally launched object", "Air resistance only",
				"Friction", "Magnetic force"], "correct": 0},
		{"question": "What is the formula for work done?",
			"options": ["W = F d", "W = m a", "W = m v", "W = P t"], "correct": 0},
		{"question": "What is the SI unit of frequency?",
			"options": ["Hertz", "Newton", "Joule", "Watt"], "correct": 0},
		{"question": "What happens to a wire's resistance as its length increases (all else equal)?",
			"options": ["Resistance increases", "Resistance decreases",
				"Resistance stays the same", "Resistance becomes zero"], "correct": 0},
		{"question": "Which of these is a scalar quantity?",
			"options": ["Mass", "Velocity", "Force", "Acceleration"], "correct": 0},
		{"question": "What is the term for light bending as it passes between different media?",
			"options": ["Refraction", "Reflection", "Diffraction", "Dispersion"], "correct": 0},
		{"question": "What is the formula for momentum?",
			"options": ["p = m v", "p = F t", "p = m a", "p = 1/2 m v²"], "correct": 0},
		{"question": "What does a negative gradient on a velocity-time graph indicate?",
			"options": ["The object is decelerating (or accelerating in the negative direction)",
				"The object is stationary", "The object is at maximum speed", "The graph is invalid"],
			"correct": 0},
		{"question": "What is the term for the amount of matter in an object?",
			"options": ["Mass", "Weight", "Volume", "Density"], "correct": 0},
		{"question": "What is terminal velocity?",
			"options": ["The constant speed reached when gravity and air resistance balance",
				"The maximum speed of any object", "The speed of sound",
				"The initial speed of a falling object"], "correct": 0},
		{"question": "What is the formula for density?",
			"options": ["mass / volume", "volume / mass", "mass x volume", "mass + volume"],
			"correct": 0},
		{"question": "What does \"half-life\" refer to in radioactive decay?",
			"options": ["The time taken for half of a radioactive sample to decay",
				"The full lifespan of an atom", "The time for all atoms to decay",
				"The mass of an atom"], "correct": 0},
		{"question": "What is the SI unit of energy?",
			"options": ["Joule", "Newton", "Watt", "Pascal"], "correct": 0},
		{"question": "What does a voltmeter measure?",
			"options": ["Potential difference (voltage)", "Current", "Resistance", "Power"],
			"correct": 0},
		{"question": "What does an ammeter measure?",
			"options": ["Electric current", "Voltage", "Resistance", "Power"], "correct": 0},
		{"question": "In a series circuit, how does current behave?",
			"options": ["It is the same at every point in the circuit", "It splits between branches",
				"It doubles at each resistor", "It becomes zero at resistors"], "correct": 0},
		{"question": "In a parallel circuit, what stays the same across each branch?",
			"options": ["Voltage", "Current", "Resistance", "Power"], "correct": 0},
		{"question": "What is the formula relating energy, power, and time?",
			"options": ["E = P t", "E = P / t", "E = t / P", "E = P + t"], "correct": 0},
		{"question": "What type of energy is stored in a stretched spring?",
			"options": ["Elastic potential energy", "Kinetic energy", "Thermal energy",
				"Chemical energy"], "correct": 0},
		{"question": "What is the principle behind a lever?",
			"options": ["A small force over a long distance can lift a large force over a short one",
				"Force is always equal on both sides", "Levers only work with pulleys",
				"Energy is created by the lever"], "correct": 0},
		{"question": "What does the term \"friction\" refer to?",
			"options": ["A force that resists relative motion between surfaces",
				"A force that only acts in space", "A type of energy", "A unit of measurement"],
			"correct": 0},
		{"question": "What is an isotope?",
			"options": ["An atom of the same element with a different number of neutrons",
				"A charged particle", "A type of molecule", "A unit of radioactivity"], "correct": 0},
		{"question": "What does the electromagnetic spectrum include?",
			"options": ["The full range of EM radiation, from radio waves to gamma rays",
				"Only visible light", "Only X-rays", "Only radio waves"], "correct": 0},
		{"question": "What is the function of a transformer in a circuit?",
			"options": ["To change the voltage of an alternating current",
				"To store electrical charge", "To measure resistance",
				"To generate electricity from nothing"], "correct": 0},
	],
	"chemistry": [
		{"question": "What is the chemical symbol for sodium?",
			"options": ["Na", "So", "Sd", "S"], "correct": 0},
		{"question": "What is the pH of a neutral solution?",
			"options": ["7", "0", "14", "1"], "correct": 0},
		{"question": "What type of bond involves the sharing of electron pairs?",
			"options": ["Covalent", "Ionic", "Metallic", "Hydrogen"], "correct": 0},
		{"question": "The atomic number of an element is determined by its number of what?",
			"options": ["Protons", "Neutrons", "Electrons only", "Mass"], "correct": 0},
		{"question": "What is produced when an acid reacts with a base?",
			"options": ["A salt and water", "Only gas", "Only heat", "Nothing"], "correct": 0},
		{"question": "What is the chemical formula for water?",
			"options": ["H₂O", "CO₂", "O₂", "H₂O₂"], "correct": 0},
		{"question": "What does \"molarity\" measure?",
			"options": ["Concentration (mol/L)", "Mass", "Volume alone", "Temperature"], "correct": 0},
		{"question": "What is an exothermic reaction?",
			"options": ["One that releases heat", "One that absorbs heat",
				"One that produces light only", "One with no energy change"], "correct": 0},
		{"question": "What is the chemical symbol for gold?",
			"options": ["Au", "Ag", "Gd", "Go"], "correct": 0},
		{"question": "What is a catalyst?",
			"options": ["A substance that speeds up a reaction without being consumed",
				"A type of acid", "A type of base", "An unstable element"], "correct": 0},
		{"question": "Avogadro's number is approximately what?",
			"options": ["6.022 × 10²³", "3.14 × 10⁰", "9.8 × 10¹", "6.674 × 10⁻¹¹"], "correct": 0},
		{"question": "Which state of matter has a fixed volume but no fixed shape?",
			"options": ["Liquid", "Solid", "Gas", "Plasma"], "correct": 0},
		{"question": "What is the process of a solid turning directly into a gas called?",
			"options": ["Sublimation", "Evaporation", "Condensation", "Melting"], "correct": 0},
		{"question": "Which subatomic particle has a negative charge?",
			"options": ["Electron", "Proton", "Neutron", "The nucleus"], "correct": 0},
		{"question": "What is the term for elements in the same column of the periodic table?",
			"options": ["Group", "Period", "Series", "Block"], "correct": 0},
		{"question": "What is the chemical formula for carbon dioxide?",
			"options": ["CO₂", "CO", "C₂O", "O₂C"], "correct": 0},
		{"question": "What type of reaction involves the loss of electrons?",
			"options": ["Oxidation", "Reduction", "Neutralization", "Combustion"], "correct": 0},
		{"question": "What does \"STP\" stand for in chemistry?",
			"options": ["Standard Temperature and Pressure", "Solid Temperature Point",
				"Standard Time Period", "State Transition Point"], "correct": 0},
		{"question": "What is the typical pH of a strong acid?",
			"options": ["Below 3", "Above 11", "Exactly 7", "Above 14"], "correct": 0},
		{"question": "What is a substance made of two or more elements chemically combined called?",
			"options": ["A compound", "A mixture", "A solution", "An alloy"], "correct": 0},
	],
	"biology": [
		{"question": "What is the powerhouse of the cell?",
			"options": ["Mitochondria", "Nucleus", "Ribosome", "Golgi apparatus"], "correct": 0},
		{"question": "What molecule carries genetic information?",
			"options": ["DNA", "RNA alone", "Protein", "Lipid"], "correct": 0},
		{"question": "What is the process by which plants make food using sunlight?",
			"options": ["Photosynthesis", "Respiration", "Transpiration", "Fermentation"], "correct": 0},
		{"question": "What is the basic unit of life?",
			"options": ["The cell", "The atom", "Tissue", "An organ"], "correct": 0},
		{"question": "What is the process of cell division that produces gametes?",
			"options": ["Meiosis", "Mitosis", "Binary fission", "Budding"], "correct": 0},
		{"question": "What are the building blocks of proteins?",
			"options": ["Amino acids", "Nucleotides", "Fatty acids", "Sugars"], "correct": 0},
		{"question": "What is natural selection?",
			"options": ["Organisms better adapted to their environment survive and reproduce",
				"Random mutation with no pattern", "Cloning", "Artificial breeding only"], "correct": 0},
		{"question": "What is the term for an organism's genetic makeup?",
			"options": ["Genotype", "Phenotype", "Karyotype", "Ecotype"], "correct": 0},
		{"question": "What is homeostasis?",
			"options": ["The maintenance of a stable internal environment", "Cell division",
				"Genetic mutation", "Species extinction"], "correct": 0},
		{"question": "What is the main role of enzymes?",
			"options": ["To speed up biochemical reactions", "To store genetic information",
				"To provide structural support", "To transport oxygen"], "correct": 0},
		{"question": "Which organelle is responsible for protein synthesis?",
			"options": ["Ribosome", "Mitochondria", "Vacuole", "Lysosome"], "correct": 0},
		{"question": "What is an ecosystem?",
			"options": ["A community of organisms interacting with their environment",
				"A single species", "A type of cell", "A food chain in isolation"], "correct": 0},
		{"question": "What is it called when two different species live together and both benefit?",
			"options": ["Mutualism", "Parasitism", "Competition", "Predation"], "correct": 0},
		{"question": "What is the main function of the circulatory system?",
			"options": ["To transport blood, nutrients, and gases", "To digest food",
				"To filter air", "To produce hormones exclusively"], "correct": 0},
		{"question": "What is a gene?",
			"options": ["A segment of DNA that codes for a protein", "A whole chromosome",
				"A type of cell", "An organelle"], "correct": 0},
		{"question": "What is the process by which cells break down glucose for energy?",
			"options": ["Cellular respiration", "Photosynthesis", "Fermentation alone", "Digestion"],
			"correct": 0},
		{"question": "What is biodiversity?",
			"options": ["The variety of life in an ecosystem", "The number of humans in an area",
				"A single species' population count", "Climate variation"], "correct": 0},
		{"question": "What is the term for a trait's alternate inherited forms?",
			"options": ["Alleles", "Genomes", "Genotypes", "Phenotypes"], "correct": 0},
		{"question": "What is the main function of white blood cells?",
			"options": ["To fight infection", "To carry oxygen", "To clot blood", "To digest food"],
			"correct": 0},
		{"question": "What is transpiration in plants?",
			"options": ["The loss of water vapour through leaves", "Photosynthesis",
				"Root growth", "Seed germination"], "correct": 0},
	],

	"statistics": [
		{"question": "What does the median of a data set represent?",
			"options": ["The middle value when ordered", "The most common value", "The average", "The range"], "correct": 0},
		{"question": "What is the interquartile range (IQR)?",
			"options": ["Q₃ − Q₁", "The highest minus lowest value", "The mean of the quartiles", "Half the range"], "correct": 0},
		{"question": "In a box plot, what does the box itself span?",
			"options": ["The middle 50% of the data", "The full range", "One standard deviation", "The outliers"], "correct": 0},
		{"question": "What is a 'population' in statistics?",
			"options": ["The entire group being studied", "A random sample", "The number of people", "The data range"], "correct": 0},
		{"question": "What does a strong positive correlation look like on a scatter plot?",
			"options": ["Points trending upward left to right", "Points trending downward", "Randomly scattered points", "A horizontal line"], "correct": 0},
		{"question": "Correlation does not imply what?",
			"options": ["Causation", "Association", "A relationship", "A trend"], "correct": 0},
		{"question": "What is a simple random sample?",
			"options": ["Every member has an equal chance of selection", "The first 30 people you find",
				"Volunteers only", "One person from each group"], "correct": 0},
		{"question": "What does a confidence interval give you?",
			"options": ["A range likely to contain the true population value", "The exact population value",
				"The sample size needed", "The margin of error only"], "correct": 0},
		{"question": "In a normal distribution, roughly what percentage lies within one standard deviation of the mean?",
			"options": ["68%", "50%", "95%", "99%"], "correct": 0},
		{"question": "What is an outlier?",
			"options": ["A value far from the rest of the data", "The largest value", "The mean", "A repeated value"], "correct": 0},
		{"question": "What is the mode of: 3, 7, 7, 2, 9?",
			"options": ["7", "3", "5.6", "9"], "correct": 0},
		{"question": "Why do we take samples instead of surveying everyone?",
			"options": ["It's cheaper and faster than a full census", "Samples are always more accurate",
				"Populations can't be measured", "It removes all bias"], "correct": 0},
		{"question": "What is sampling bias?",
			"options": ["When a sample isn't representative of the population", "Any error in the data",
				"Using too large a sample", "Rounding numbers incorrectly"], "correct": 0},
		{"question": "What does the 'expected value' of a random variable mean?",
			"options": ["The long-run average outcome", "The most likely single outcome",
				"The maximum possible value", "The variance"], "correct": 0},
		{"question": "If two events are independent, what is P(A and B)?",
			"options": ["P(A) × P(B)", "P(A) + P(B)", "P(A) − P(B)", "P(A) ÷ P(B)"], "correct": 0},
	],
	"economics": [
		{"question": "What does the law of demand state?",
			"options": ["As price rises, quantity demanded falls", "As price rises, demand rises",
				"Demand is always constant", "Supply determines demand"], "correct": 0},
		{"question": "What is opportunity cost?",
			"options": ["The value of the next best alternative given up", "The money price of a good",
				"The cost of production", "Total spending"], "correct": 0},
		{"question": "What happens at market equilibrium?",
			"options": ["Quantity supplied equals quantity demanded", "Supply exceeds demand",
				"Prices are at their lowest", "Profit is maximised"], "correct": 0},
		{"question": "What is inflation?",
			"options": ["A sustained rise in the general price level", "A rise in unemployment",
				"An increase in exports", "A fall in interest rates"], "correct": 0},
		{"question": "What does GDP measure?",
			"options": ["The total value of goods and services produced", "Government spending only",
				"The money supply", "Average household income"], "correct": 0},
		{"question": "In New Zealand, which body sets the Official Cash Rate?",
			"options": ["The Reserve Bank of New Zealand", "Parliament", "Treasury", "Statistics NZ"], "correct": 0},
		{"question": "What is a subsidy?",
			"options": ["A government payment to lower production costs", "A tax on imports",
				"A limit on production", "A price ceiling"], "correct": 0},
		{"question": "What does 'elastic demand' mean?",
			"options": ["Quantity demanded changes a lot when price changes", "Demand never changes",
				"Supply is fixed", "Price is fixed by government"], "correct": 0},
		{"question": "What is a tariff?",
			"options": ["A tax on imported goods", "A subsidy for exporters",
				"A limit on immigration", "A type of income tax"], "correct": 0},
		{"question": "What is meant by 'scarcity' in economics?",
			"options": ["Limited resources against unlimited wants", "A shortage caused by hoarding",
				"High prices", "Low production"], "correct": 0},
		{"question": "What typically happens to demand for a normal good when incomes rise?",
			"options": ["Demand increases", "Demand decreases", "Demand stays the same", "Supply falls"], "correct": 0},
		{"question": "What is a recession commonly defined as?",
			"options": ["Two consecutive quarters of negative GDP growth", "Any fall in share prices",
				"Rising inflation", "A government deficit"], "correct": 0},
		{"question": "What does a price ceiling set?",
			"options": ["A legal maximum price", "A legal minimum price", "A tax rate", "A production quota"], "correct": 0},
		{"question": "What is the primary sector of an economy?",
			"options": ["Extraction of raw materials", "Manufacturing", "Services", "Retail"], "correct": 0},
		{"question": "Why might a government run a budget deficit during a downturn?",
			"options": ["To stimulate demand and support employment", "To reduce national debt",
				"To increase interest rates", "To lower exports"], "correct": 0},
	],
	"geography": [
		{"question": "What causes earthquakes along New Zealand's Alpine Fault?",
			"options": ["Movement between the Pacific and Australian plates", "Volcanic eruptions only",
				"Ocean currents", "Glacial melting"], "correct": 0},
		{"question": "What is erosion?",
			"options": ["The wearing away and transport of material", "The build-up of sediment",
				"The formation of rock", "A type of rainfall"], "correct": 0},
		{"question": "What is a natural hazard?",
			"options": ["A natural process that threatens people or property", "Any severe weather",
				"A protected area", "A type of landform"], "correct": 0},
		{"question": "What does 'urbanisation' mean?",
			"options": ["Growth in the proportion of people living in cities", "Building more roads",
				"Population decline", "Farming intensification"], "correct": 0},
		{"question": "What is a contour line on a topographic map?",
			"options": ["A line joining points of equal elevation", "A road", "A river", "A border"], "correct": 0},
		{"question": "What type of volcano is Mt Taranaki?",
			"options": ["A stratovolcano (composite cone)", "A shield volcano", "A caldera", "A cinder cone"], "correct": 0},
		{"question": "What is the rain shadow effect?",
			"options": ["Drier conditions on the leeward side of mountains", "Heavy rain on all sides",
				"Rain only at night", "Fog in valleys"], "correct": 0},
		{"question": "What does 'sustainability' mean in a geographic context?",
			"options": ["Meeting present needs without compromising future generations",
				"Stopping all development", "Maximising short-term output", "Population control"], "correct": 0},
		{"question": "What is a delta?",
			"options": ["A landform where a river deposits sediment at its mouth", "A mountain pass",
				"A type of glacier", "A coastal cliff"], "correct": 0},
		{"question": "What drives the water cycle?",
			"options": ["Energy from the sun", "Tidal forces", "Plate tectonics", "Wind alone"], "correct": 0},
		{"question": "What is population density?",
			"options": ["The number of people per unit area", "Total population", "Birth rate", "Migration rate"], "correct": 0},
		{"question": "Which process formed the Southern Alps?",
			"options": ["Tectonic uplift at a plate boundary", "Volcanic deposition",
				"Wind erosion", "Coral growth"], "correct": 0},
		{"question": "What is a push factor in migration?",
			"options": ["Something driving people away from a place", "Something attracting people to a place",
				"Government policy only", "Natural population growth"], "correct": 0},
		{"question": "What does GIS stand for?",
			"options": ["Geographic Information System", "Global Industry Standard",
				"Geological Inspection Survey", "Ground Imaging Sensor"], "correct": 0},
		{"question": "What is a glacier?",
			"options": ["A slow-moving mass of ice", "A frozen lake", "A snow field", "A type of river"], "correct": 0},
	],
	"digital_technologies": [
		{"question": "What is an algorithm?",
			"options": ["A step-by-step procedure for solving a problem", "A programming language",
				"A type of computer", "A database"], "correct": 0},
		{"question": "What does a variable do in programming?",
			"options": ["Stores a value that can change", "Repeats code", "Ends the program", "Draws graphics"], "correct": 0},
		{"question": "What is a loop used for?",
			"options": ["Repeating a block of code", "Storing data", "Naming a function", "Closing a file"], "correct": 0},
		{"question": "What does 'debugging' mean?",
			"options": ["Finding and fixing errors in code", "Writing documentation",
				"Deleting a program", "Speeding up a computer"], "correct": 0},
		{"question": "In binary, what is the decimal number 5?",
			"options": ["101", "110", "011", "111"], "correct": 0},
		{"question": "What is a function in programming?",
			"options": ["A reusable named block of code", "A single variable", "A comment", "An error message"], "correct": 0},
		{"question": "What does HTML primarily define?",
			"options": ["The structure and content of a web page", "The colours of a page",
				"Server logic", "Database queries"], "correct": 0},
		{"question": "What is the purpose of a database index?",
			"options": ["To speed up searching for records", "To store backups",
				"To encrypt the data", "To compress files"], "correct": 0},
		{"question": "What is an iterative design process?",
			"options": ["Repeatedly refining a solution through testing and feedback",
				"Designing everything once upfront", "Copying an existing design", "Skipping the planning stage"], "correct": 0},
		{"question": "What does 'user interface' refer to?",
			"options": ["How a person interacts with a system", "The source code",
				"The server hardware", "The network protocol"], "correct": 0},
		{"question": "What is a conditional statement?",
			"options": ["Code that runs only if something is true", "Code that always runs",
				"A type of variable", "A loop counter"], "correct": 0},
		{"question": "Why is version control useful?",
			"options": ["It tracks changes and lets you revert to earlier versions", "It makes code run faster",
				"It removes all bugs", "It compresses files"], "correct": 0},
		{"question": "What is phishing?",
			"options": ["Tricking someone into revealing sensitive information", "A type of firewall",
				"A programming error", "A backup method"], "correct": 0},
		{"question": "What does 'open source' mean?",
			"options": ["The source code is publicly available to view and modify", "The software is unfinished",
				"It only runs online", "It has no licence at all"], "correct": 0},
		{"question": "What is the purpose of testing with real users?",
			"options": ["To find usability problems the designer missed", "To speed up the program",
				"To satisfy legal rules only", "To reduce file size"], "correct": 0},
	],

	"history": [
		{"question": "What was signed at Waitangi in 1840?", "options": ["The Treaty of Waitangi", "The Declaration of Independence", "The Constitution Act", "The Land Wars Accord"], "correct": 0},
		{"question": "What does a 'primary source' mean to a historian?", "options": ["Evidence created at the time being studied", "A textbook about the period", "A modern documentary", "A summary written later"], "correct": 0},
		{"question": "What were the New Zealand Wars largely fought over?", "options": ["Land and sovereignty", "Trade routes", "Religion", "Gold claims only"], "correct": 0},
		{"question": "What is historical 'context'?", "options": ["The wider circumstances surrounding an event", "The date it happened", "A list of causes", "The historian's opinion"], "correct": 0},
		{"question": "Which event triggered the start of World War I?", "options": ["The assassination of Archduke Franz Ferdinand", "The invasion of Poland", "The sinking of the Lusitania", "The Treaty of Versailles"], "correct": 0},
		{"question": "What was the Gallipoli campaign?", "options": ["A failed WWI allied landing in Ottoman territory", "A naval battle in the Pacific", "A WWII desert campaign", "A peace conference"], "correct": 0},
		{"question": "What does 'bias' mean in a historical source?", "options": ["A slant reflecting the creator's perspective", "A factual error", "An unclear date", "A missing author"], "correct": 0},
		{"question": "What was the 1981 Springbok Tour controversy about?", "options": ["Sporting contact with apartheid South Africa", "Stadium funding", "Player wages", "Broadcasting rights"], "correct": 0},
		{"question": "What is meant by 'consequence' in historical study?", "options": ["The results and effects that followed an event", "The cause of an event", "The date range", "The sources used"], "correct": 0},
		{"question": "What was the Great Depression?", "options": ["A severe worldwide economic downturn in the 1930s", "A WWI battle", "A famine in the 1800s", "A political party"], "correct": 0},
		{"question": "What is a 'secondary source'?", "options": ["An account produced after the event by someone not present", "A diary from the time", "A photograph taken at the scene", "An official record of the day"], "correct": 0},
		{"question": "What was the purpose of the 1975 Waitangi Tribunal?", "options": ["To investigate Treaty breaches and claims", "To run elections", "To set tax rates", "To manage immigration"], "correct": 0},
		{"question": "Why do historians compare multiple sources?", "options": ["To test reliability and build a fuller picture", "To find the longest one", "To pick the most recent", "To avoid primary evidence"], "correct": 0},
		{"question": "What does 'significance' mean when assessing a historical event?", "options": ["How much it mattered and to whom, over time", "How long it lasted", "How many sources exist", "How recent it was"], "correct": 0},
		{"question": "What was the women's suffrage milestone of 1893 in New Zealand?", "options": ["Women won the right to vote in national elections", "Women could stand for Parliament", "Equal pay was introduced", "Women gained property rights"], "correct": 0},
	],
	"media_studies": [
		{"question": "What does 'target audience' mean?", "options": ["The specific group a media product is made for", "Everyone who sees it", "The production crew", "The distributor"], "correct": 0},
		{"question": "What is a 'genre' in media?", "options": ["A category with shared conventions", "A camera technique", "A distribution method", "A funding model"], "correct": 0},
		{"question": "What does 'mise-en-scène' refer to?", "options": ["Everything arranged within the frame", "The editing rhythm", "The soundtrack", "The script"], "correct": 0},
		{"question": "What is a low-angle shot typically used to suggest?", "options": ["Power or dominance", "Weakness", "Confusion", "Distance"], "correct": 0},
		{"question": "What is 'representation' in media studies?", "options": ["How groups and ideas are portrayed", "The number of viewers", "The budget", "The release schedule"], "correct": 0},
		{"question": "What does 'convergence' describe?", "options": ["Different media technologies merging together", "Falling audience numbers", "Censorship", "A type of camera move"], "correct": 0},
		{"question": "What is the purpose of a establishing shot?", "options": ["To show where a scene takes place", "To end a scene", "To show a character's face", "To hide information"], "correct": 0},
		{"question": "What is a 'media conglomerate'?", "options": ["A large company owning many media outlets", "A government regulator", "An audience group", "A film festival"], "correct": 0},
		{"question": "What does 'narrative structure' mean?", "options": ["How a story is organised and ordered", "The camera equipment used", "The advertising budget", "The rating given"], "correct": 0},
		{"question": "What is product placement?", "options": ["Paid inclusion of branded goods in content", "Shelf arrangement in shops", "A type of edit", "A rating system"], "correct": 0},
		{"question": "Why might a documentary still not be fully objective?", "options": ["Editing and framing choices shape the message", "Documentaries never use real footage", "They are always scripted", "They avoid interviews"], "correct": 0},
		{"question": "What is 'binary opposition' in media analysis?", "options": ["Contrasting pairs used to build meaning", "Two cameras filming at once", "A digital file format", "Split-screen editing"], "correct": 0},
		{"question": "What does a 'close-up' typically emphasise?", "options": ["Emotion and detail", "Setting", "Scale", "Time passing"], "correct": 0},
		{"question": "What is meant by 'audience positioning'?", "options": ["Guiding viewers toward a particular reading", "Where seats are in a cinema", "Sorting viewers by age", "Broadcast scheduling"], "correct": 0},
		{"question": "What is a 'sub-genre'?", "options": ["A more specific category within a genre", "A failed genre", "A foreign-language genre", "A genre with no conventions"], "correct": 0},
	],
	"physical_education": [
		{"question": "What does 'cardiovascular endurance' measure?", "options": ["How long the heart and lungs can sustain activity", "Maximum lifting strength", "Joint flexibility", "Reaction speed"], "correct": 0},
		{"question": "What is the purpose of a warm-up?", "options": ["Raise body temperature and prepare muscles", "Burn maximum calories", "Cause fatigue before training", "Replace stretching entirely"], "correct": 0},
		{"question": "What does the FITT principle stand for?", "options": ["Frequency, Intensity, Time, Type", "Fitness, Injury, Training, Technique", "Force, Impact, Tempo, Timing", "Flexibility, Intensity, Talent, Training"], "correct": 0},
		{"question": "Which energy system dominates in a 100m sprint?", "options": ["ATP-PC (anaerobic alactic)", "Aerobic", "Lactic acid only", "Fat oxidation"], "correct": 0},
		{"question": "What is a skill-related fitness component?", "options": ["Agility", "Body composition", "Cardiovascular endurance", "Flexibility"], "correct": 0},
		{"question": "What causes delayed onset muscle soreness (DOMS)?", "options": ["Microscopic muscle damage from unfamiliar exercise", "Dehydration only", "Lactic acid remaining in muscle for days", "Low blood sugar"], "correct": 0},
		{"question": "What does 'progressive overload' mean?", "options": ["Gradually increasing training demand over time", "Training to failure every session", "Reducing rest to zero", "Always using maximum weight"], "correct": 0},
		{"question": "What is the recommended response for a soft tissue injury?", "options": ["Rest, ice, compression, elevation", "Heat and vigorous massage", "Continue training through it", "Stretch aggressively"], "correct": 0},
		{"question": "What is 'intrinsic motivation'?", "options": ["Doing something for personal satisfaction", "Competing for a trophy", "Training for money", "Avoiding punishment"], "correct": 0},
		{"question": "What role does hauora play in NZ health education?", "options": ["A holistic model of wellbeing with several dimensions", "A fitness test", "A sports league", "A nutrition supplement"], "correct": 0},
		{"question": "What is aerobic exercise?", "options": ["Sustained activity using oxygen for energy", "Short maximal bursts", "Only weight training", "Stretching routines"], "correct": 0},
		{"question": "Why is hydration important during exercise?", "options": ["It maintains blood volume and temperature regulation", "It builds muscle directly", "It replaces protein", "It prevents all injury"], "correct": 0},
		{"question": "What does 'biomechanics' study?", "options": ["The mechanics of human movement", "Sports psychology", "Team tactics", "Nutrition timing"], "correct": 0},
		{"question": "What is a 'sedentary lifestyle' associated with?", "options": ["Increased risk of chronic health conditions", "Improved endurance", "Higher bone density", "Better flexibility"], "correct": 0},
		{"question": "What is the main function of carbohydrates for an athlete?", "options": ["Primary fuel source for working muscles", "Building muscle tissue", "Insulating the body", "Transporting oxygen"], "correct": 0},
	],
}


## Shuffles a question's options and remaps its `correct` index to follow the
## right answer to its new position. Almost every question in this file was
## authored with the correct answer as option 0, so without this the quiz is
## trivially gameable by always picking the first choice.
static func shuffle_question(q: Dictionary) -> Dictionary:
	var shuffled: Dictionary = q.duplicate(true)
	var correct_text: String = shuffled.options[shuffled.correct]
	shuffled.options.shuffle()
	shuffled.correct = shuffled.options.find(correct_text)
	return shuffled


## Returns `count` random questions for `subject` (no repeats within a session).
func get_session_questions(subject: String, count: int = 5) -> Array:
	if not _banks.has(subject):
		push_warning("StudyData: unknown subject '%s'" % subject)
		return []
	var pool: Array = _banks[subject].duplicate(true)
	pool.shuffle()
	var selected: Array = pool.slice(0, min(count, pool.size()))
	var result: Array = []
	for q in selected:
		result.append(shuffle_question(q))
	return result


## All subject keys this bank supports — useful for building the subject-select UI.
func get_subjects() -> Array:
	return _banks.keys()


## Total question count across all subjects — handy for a debug/sanity check.
func get_total_question_count() -> int:
	var total: int = 0
	for subject in _banks:
		total += _banks[subject].size()
	return total
